mysite/myauth/urls.py
from django.urls import path
from .views import get_cookie_view, set_cookie_view, set_session_view, get_session_view, MylogoutView, AboutMeView, RegisterView
from django.contrib.auth.views import LoginView


app_name = 'myauth'

urlpatterns = [
    # path('login/', login_view, name='login'),
    path('login/', LoginView.as_view(template_name="myauth/login.html", redirect_authenticated_user=True), name='login'),
    path('cookie/set/', set_cookie_view, name='cookie-set'),
    path('cookie/get', get_cookie_view, name='cookie-get'),
    path('session/set/', set_session_view, name='session-set'),
    path('session/get/', get_session_view, name='session-get'),
    # path('logout/', logout_view, name='logout'),
    path('logout/', MylogoutView.as_view(), name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('req/', include('requestdataapp.urls')),
    path('myauth/', include('myauth.urls')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

mysite/shopapp/urls.py
from django.urls import path

from .views import ( 
    ShopIndexView, 
    GroupsListViev,
    ProductDetailsView,
    ProductListView,
    OrdersListView,
    OrderDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView)


app_name = 'shopapp'

urlpatterns = [
    path('', ShopIndexView.as_view(), name='index'),
    path('groups/', GroupsListViev.as_view(), name='groups'),
    path('products/', ProductListView.as_view(), name='products_list'),
    path('orders/', OrdersListView.as_view(), name='order_list'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', ProductDetailsView.as_view(), name='product_details'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/archived/', ProductDeleteView.as_view(), name='product_delete'), 
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_details'),
]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models


def product_prewiew_directory_path(instance: "Product", filename: str) -> str:
    return 'products/product_{pk}/preview/{filename}'.format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    class Meta:
        ordering = ['name', 'price']
        # db_table = 'tech_products'
        # verbose_name_plural ='Products'

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True,upload_to='')

    # @property (перенес в админку)
    # def description_short(self) -> str:
    #     if len(self.description) < 48:
    #         return self.description
    #     return self.description[:48] + '...'

    def __str__(self) -> str:
        return f'Product(pk={self.pk}, name={self.name!r})'

class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')
    receipt = models.FileField(null=True, upload_to='orders/receipts')

mysite/shopapp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Product
from django.contrib.auth.models import Group

# from django.core import validators

# class ProductForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     price = forms.DecimalField(min_value=1, max_value=100000)
#     description = forms.CharField(
#         label='Product description',
#         widget=forms.Textarea(attrs={"rows": 5, "cols": 20}),
#         validators=[validators.RegexValidator(
#             regex='Product',
#             message='Product name should start with "Product"',
#         )]
#     )

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'description', 'discount']
        

class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ['name']

mysite/shopapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import Group, User
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin

from .forms import ProductForm
from .models import Product
from .models import Order
from .forms import GroupForm

class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999),
        ]
        context = {
            'products': products,
        }
        return render(request, 'shopapp/shop-index.html', context=context)
    
class GroupsListViev(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            'form': GroupForm(),
            'groups': Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)
    def post(self, request: HttpRequest) -> HttpResponse:
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect(request.path)
    
# class ProductDetailsView(View):
#     def get(self, request: HttpRequest, pk: int) -> HttpResponse:
#         product = get_object_or_404(Product, pk=pk)
#         context = {
#             'product': product,
#         }
#         return render(request, 'shopapp/products-details.html', context=context)

class ProductDetailsView(DetailView):
    template_name = 'shopapp/products-details.html'
    model = Product
    # queryset = Product.objects.prefetch_related('orders')
    context_object_name = 'product'

# class ProductListView(TemplateView):
#     template_name = 'shopapp/products-list.html'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['products'] = Product.objects.all()
#         return context

class ProductListView(ListView):
    template_name = 'shopapp/products-list.html'
    # model = Product
    context_object_name = 'products'
    queryset = Product.objects.filter(archived=False)

# def products_list(request):
#     context = {
#         'products': Product.objects.all(),
#     }
#     return render(request, 'shopapp/products-list.html', context=context)


# def create_product(request):
#     if request.method == 'POST':
#         form = ProductForm(request.POST)
#         if form.is_valid():
#             #name = form.cleaned_data['name']
#             #price = form.cleaned_data['price']
#             # Product.objects.create(**form.cleaned_data)
#             form.save()
#             url = reverse('shopapp:products_list')
#             return redirect(url)
#     else:
#         form = ProductForm(request.POST)
#     context = {
#         'form': form,
#     }
#     return render(request, 'shopapp/create-product.html', context=context)

class ProductCreateView(CreateView):
    model = Product
    fields = "name", "price", "description", "discount"
    success_url = reverse_lazy("shopapp:products_list")

# def orders_list(request):
#     context = {
#         'orders': Order.objects.select_related('user').prefetch_related("products").all(),

#     }
#     return render(request, 'shopapp/orders-list.html', context=context)

# class OrdersListView(LoginRequiredMixin, ListView):
#     queryset = (
#         Order.objects
#         .select_related('user')
#         .prefetch_related("products")
#     )

class OrdersListView(LoginRequiredMixin, ListView):
    model = Order

    def get_queryset(self):
        user = self.request.user
        if user.has_perm('orders.view_order'):
            return Order.objects.select_related('user').prefetch_related("products")
        return Order.objects.filter(user=user).select_related('user').prefetch_related("products")

# class OrderDetailView(PermissionRequiredMixin, DetailView): # PermissionRequiredMixin не работает
#     permission_required = 'shopapp.view_order'
#     queryset = (
#         Order.objects
#         .select_related('user')
#         .prefetch_related("products")
#     )

class OrderDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Order
    queryset = Order.objects.select_related('user').prefetch_related('products')

    def test_func(self):
        order = self.get_object()
        user = self.request.user
        return user == order.user or user.has_perm('shopapp.view_order')  

class ProductUpdateView(UpdateView):
    model = Product
    fields = "name", "price", "description", "discount"
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse(
            "shopapp:product_details",
            kwargs={"pk": self.object.pk},
        )

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    {% block body %}
    {% endblock %}

    <div>
        {% now 'H:i' %}
    </div>
    <div>
        {% now 'l' as current_weekday %}
        Today is {{ current_weekday }}
    </div>
</body>
</html>

mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create product</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            <button type="submit">Create</button>
            {{ form.as_p }}
        </form>
    </div>    

    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %} Groups {% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div> 
        {% if not groups %}
            <h3>No groups yet</h3>
        {% else %}
            <ul>{% for group in groups %}
                    <li> 
                        <div>
                            {{ group.name }} 
                        </div>
                        <div>
                            <ul>
                                {% for permission in group.permissions.all %}
                                    <li>
                                        {{ permission.name }}
                                        (<code>{{ permission.codename }}</code>)
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                {% endfor %}
            </ul>

        {% endif %}
        
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order #{{ object.pk }}
{% endblock %}

{% block body %}
    <h1>Order #{{ object.pk }}</h1>
    <div>
                <p>Order by {% firstof object.user.first_name order.user.username %}</p>
                <p>Promocode: <code>{{ object.promocode }}</code></p>
                <p>Delivery address: {{ object.delivery_address }}</p>
                <div>
                    Products in order:

                    <ul>
                        {% for product in object.products.all %}
                        <li>{{ product.name }} for ${{ product.price }}</li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
            <div>
                <a href="{% url 'shopapp:order_list' %}">Back to orders list</a>
            </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders
{% endblock %}

{% block body %}

    <h1>Orders:</h1>
    {% if object_list %}
    <div> 
        {% for order in object_list %}
            <div>
                <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">Details #{{ order.pk }}</a></p>
                <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                <p>Promocode: <code>{{ order.promocode }}</code></p>
                <p>Delivery address: {{ order.delivery_address }}</p>
                <div>
                    Products in order:

                    <ul>
                        {% for product in order.products.all %}
                        <li>{{ product.name }} for ${{ product.price }}</li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
        <h3>No orders yet</h3>
    {% endif %}
    <div>
        <a href="{% url 'shopapp:product_create' %}">Create a new
    </div>
    <div><h1> Hello world </h1></div>

{% endblock%}

mysite/shopapp/templates/shopapp/orders-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders
{% endblock %}

{% block body %}

    <h1>Orders:</h1>
    {% if orders %}
    <div> 
        {% for order in orders %}
            <div>
                <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                <p>Promocode: <code>{{ order.promocode }}</code></p>
                <p>Delivery address: {{ order.delivery_address }}</p>
                <div>
                    Products in order:

                    <ul>
                        {% for product in order.products.all %}
                        <li>{{ product.name }} for ${{ product.price }}</li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
        <h3>No orders yet</h3>
    {% endif %}

{% endblock%}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm Archived {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to Archived {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}">Back to {{ object.name }}</a>
    </div>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archived</button>
        </form>
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create a new product
{% endblock %}

{% block body %}
    <h1>Create a new product</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create </button>
        </form> 
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>

{% endblock%}

mysite/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update product
{% endblock %}

{% block body %}
    <h1>Update a new product</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update </button>
        </form> 
    </div>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}">Back to products # {{ object.pk }}</a>
    </div>

{% endblock%}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product #{{ product.pk }}
{% endblock %}

{% block body %}
    <h1>Product <strong>{{ product.name }}</strong></h1>
    <div>
        <div>
            Description: <em>{{ product.description }}</em>
        </div>
        <div>
            Price: {{ product.price }}
        </div>
        <div>
            Discount: {{ product.discount }}
        </div>
        <div>
            Archived: {{ product.archived }}
        </div>
    <div>
        </div>
            <a href="{% url 'shopapp:product_update' pk=product.pk %}">Update product</a>
        </div>
        <div>
            <a href="{% url 'shopapp:product_delete' pk=product.pk %}">Archived product</a>
        </div>
        <div>
            <a href="{% url 'shopapp:products_list' %}">Back to product list</a>
        </div>
{% endblock%}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %} 
    Products list
{% endblock %}

{% block body %}
    <h1>Products:</h1>
    {% if products %}
        <div>
            {% for product in products %}
            <div>
                <p><a href="{% url 'shopapp:product_details' pk=product.pk %}">Name: {{ product.name }}</a></p>
                <p>Price: {{ product.price }}</p>
                <p>Discount: {% firstof product.discount 'no discount'%}</p>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>No products yet</h3>
    {% endif %}

    <div>
        <a href="{% url 'shopapp:product_create' %}">Create a new product</a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %} Shop Index {% endblock %}

{% block body %}
    <h1>Shop Index</h1>
    <div>
        <ul>
            {% for name, price in products %}
            <li>{{ name }} for ${{ price }}</li>

            {% comment %} {% if name|length == 7 %}
                <span> Lucky products </span> {% endcomment %}
            {% comment %} {% endif %} {% endcomment %}
            
            {% empty %} 
                No products here
            {% endfor %}
        </ul>
    </div>


    <div>{% lorem 3 p random %}</div>

{% endblock %}